"""Precompute word -> lfn spelling, so the respeller can be ported without porting code.

The Python front-end does two things per word: look the pronunciation up, and rewrite
it in lfn letters. Both are deterministic, so the whole thing collapses into one
lookup table -- which is what a Kotlin, Swift or C++ port actually needs. Ship this
file with the voice and a mobile respeller is a hash-map read plus a join, no IPA
handling and no phoneme tables.

    word<TAB>lfn spelling

What a port still has to decide is what to do about a word that is not in the table.
Under `lang=lfn` an unrespelled English word is read with Latin letter values -- `the`
as /thˈe/ -- so leaving it alone sounds wrong. Two honest options: send the utterance
through the espeak-en dictionary route instead (plain text, `lang=en-us`, correct
names but English vowels), or accept the odd word. This library asks espeak-en for the
pronunciation and respells that, which a port can only do with espeak available.

    python tools/export_lfn_lexicon.py --out build/lfn-lexicon.tsv.gz
"""

from __future__ import annotations

import argparse
import gzip
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from poto_tts.respell import respell  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default="build/lfn-lexicon.tsv.gz")
    args = ap.parse_args()

    from ghana_english_g2p.core import _load_lexicon

    lexicon = _load_lexicon()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    written = skipped = 0
    with gzip.open(out, "wt", encoding="utf-8") as fh:
        fh.write("# word\tlfn spelling -- generated by poto-tts "
                 "tools/export_lfn_lexicon.py\n")
        for word in sorted(lexicon):
            spelling = respell(lexicon[word][0])
            if not spelling:
                skipped += 1
                continue
            fh.write(f"{word}\t{spelling}\n")
            written += 1

    size = out.stat().st_size
    print(f"{written} words -> {out} ({size/1e6:.1f} MB)", file=sys.stderr)
    if skipped:
        print(f"  {skipped} words respelled to nothing and were left out",
              file=sys.stderr)
    for sample in ("kwabena", "achimota", "okuapenhene", "nyankpani", "the", "policy"):
        if sample in lexicon:
            print(f"  {sample:14s} {respell(lexicon[sample][0])}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
